# Generated by Django 4.2 on 2023-05-09 17:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Portfolio name')),
                ('image', models.ImageField(upload_to='static/user_img')),
                ('data_brith', models.DateField(help_text='Day of the event', verbose_name='Day of the data brith')),
                ('address', models.CharField(max_length=200, verbose_name='Portfolio address')),
                ('email', models.CharField(max_length=100, verbose_name='Portfolio email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Portfolio phone number')),
                ('complate_project', models.IntegerField()),
                ('document', models.FileField(upload_to='documents/', verbose_name='Upload You CV')),
            ],
            options={
                'verbose_name': 'About Me Data',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(help_text='Day of the event', verbose_name='Day of the Experiance')),
                ('posisions', models.CharField(max_length=200, verbose_name='Experiance posisions')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'My Experiance',
            },
        ),
        migrations.CreateModel(
            name='ImageHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/user_img')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Skills title')),
                ('skill_style_with', models.CharField(max_length=10, verbose_name='Skills style with')),
                ('skill_style_span', models.CharField(max_length=10, verbose_name='Skills style span')),
            ],
            options={
                'verbose_name': 'Language Skills',
            },
        ),
        migrations.CreateModel(
            name='MySocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('icon', models.CharField(max_length=250)),
                ('icon_info', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectForingKeyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Project title')),
            ],
            options={
                'verbose_name': 'Project Name',
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('image', models.ImageField(upload_to='static/project_img')),
                ('year_completed', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.projecttag')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.projectforingkeyname')),
            ],
            options={
                'verbose_name': 'Project Name',
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.projectname')),
            ],
        ),
        migrations.CreateModel(
            name='MyBlog',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.blogtag')),
            ],
            options={
                'verbose_name': 'My Blog',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.myblog')),
            ],
        ),
    ]
